config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace 'api', defaults: { format: 'json' } do
    namespace 'v1' do
      resources :tickets, only: [:index, :create, :show, :update] do
        resources :comments, only: [:index, :create, :show]
      end

      resource :profile, only: [:show]
      resource :session, only: [:create, :destroy]
    end
  end

  namespace :agent do
    resources :tickets, only: [:index, :show, :update] do
      resources :comments, only: [:create]
    end
    resources :users, except: :destroy
    root to: 'tickets#index'
  end

  root 'welcome#index'

  get '(*path)', to: 'welcome#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return unless user
    can(:create, Ticket)
    can([:show, :update], Ticket) { |ticket| ticket.user_id == user.id }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :ticket
  belongs_to :user

  validates :content, presence: true, length: {maximum: 65_535, allow_blank: true}
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  attr_accessor :comment

  belongs_to :user
  belongs_to :agent, class_name: :User, required: false
  has_many :comments

  validates :title, presence: true, length: { maximum: 255 }
  validates :status, inclusion: { in: %w(open closed), message: '%{value} is not a valid status' }
  validates :comment, presence: true, on: :create

  before_validation :build_first_comment, on: :create

  def build_first_comment
    return unless comment.present? && user
    comments.new(content: comment, user: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :omniauthable, :registerable, :recoverable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :comments

  validates :name, presence: true, length: { maximum: 255 }

  scope :agent, ->(val = true) { where(agent: val) }
  scope :admin, ->(val = true) { where(admin: val) }

  def password=(val)
    super if val && !val.empty?
  end

  prepend(Module.new do
    def password_confirmation=(val)
      super if val && !val.empty?
    end
  end)
end

app/controllers/agent/base_controller.rb
module Agent
  class BaseController < ApplicationController
    abstract!

    layout 'agent'

    before_action :ensure_agent

    def ensure_agent
      ensure_current_user
      raise CanCan::AccessDenied.new('For agent only', action_name) unless current_user.agent? || current_user.admin?
    end

    def ensure_admin
      ensure_current_user
      raise CanCan::AccessDenied.new('For agent only', action_name) unless current_user.admin?
    end
  end
end

app/controllers/agent/comments_controller.rb
module Agent
  class CommentsController < BaseController
    inherit_resources
    actions :create
    belongs_to :ticket

    def permitted_params
      params[:comment][:user_id] = current_user.id
      params.permit(comment: [:content, :user_id])
    end
  end
end

app/controllers/agent/tickets_controller.rb
module Agent
  class TicketsController < BaseController
    inherit_resources
    actions :index, :show, :update

    def permitted_params
      params.permit(ticket: [:status, :agent_id])
    end
  end
end

app/controllers/agent/users_controller.rb
module Agent
  class UsersController < BaseController
    inherit_resources

    actions :all, except: [:destroy]

    before_action :ensure_admin

    def permitted_params
      params.permit(user: [:email, :name, :password, :password_confirmation, :agent, :admin])
    end
  end
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ApplicationController
      abstract!

      include CsrfCookie
      respond_to :json

      before_action :ensure_current_user
    end
  end
end

app/controllers/api/v1/comments_controller.rb
module Api
  module V1
    class CommentsController < BaseController
      def index
        comments = current_user.tickets.find(params[:ticket_id]).comments.all

        render locals: { comments: comments }
      end

      def create
        comment = Ticket.find(params[:ticket_id]).comments.new(ticket_params.merge(user_id: current_user.id))
        if comment.save
          render(
            action: :show,
            locals: { comment: comment },
            status: :created,
            location: url_for(action: :show, id: comment)
          )
        else
          render json: { errors: comment.errors }, status: :unprocessable_entity
        end
      end

      def show
        comment = current_user.tickets.find(params[:ticket_id]).comments.find(params[:id])

        render locals: { comment: comment }
      end

      private

      def ticket_params
        params.require(:comment).permit(:content)
      end
    end
  end
end

app/controllers/api/v1/profiles_controller.rb
module Api
  module V1
    class ProfilesController < BaseController
      def show
        render action: :show
      end
    end
  end
end

app/controllers/api/v1/sessions_controller.rb
module Api
  module V1
    class SessionsController < BaseController
      prepend_before_action :allow_params_authentication!, only: :create
      skip_before_action :ensure_current_user
      skip_before_action :verify_authenticity_token, only: :create

      def create
        if warden.authenticated?(:user)
          return render json: {error: t('devise.failure.already_authenticated')},
                        status: :unprocessable_entity
        end
        user = warden.authenticate!(scope: :user)
        sign_in(:user, user)
        head :created
      end

      def destroy
        sign_out
        head :no_content
      end
    end
  end
end

app/controllers/api/v1/tickets_controller.rb
module Api
  module V1
    class TicketsController < BaseController
      def index
        tickets = current_user.tickets.all

        render locals: {tickets: tickets}
      end

      def create
        ticket = current_user.tickets.new(ticket_params)
        if ticket.save
          render(
            action: :show,
            locals: { ticket: ticket },
            status: :created,
            location: url_for(action: :show, id: ticket)
          )
        else
          render json: { errors: ticket.errors }, status: :unprocessable_entity
        end
      end

      def show
        ticket = Ticket.find(params[:id])

        render locals: {ticket: ticket}
      end

      def update
        ticket = Ticket.find(params[:id])

        authorize! :update, ticket

        if ticket.update(ticket_params)
          render(
            action: :show,
            locals: { ticket: ticket },
            status: :accepted,
            location: url_for(action: :show, id: ticket)
          )
        else
          render json: { errors: ticket.errors }, status: :unprocessable_entity
        end

      end

      private

      def ticket_params
        if action_name == 'update'
          params.require(:ticket).permit(:status)
        else
          params.require(:ticket).permit(:title, :comment)
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  abstract!

  protect_from_forgery with: :exception

  def ensure_current_user
    warden.authenticate!(scope: :user)
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/concerns/csrf_cookie.rb
module CsrfCookie
  def self.included(base)
    base.after_action :add_csrf_cookie
  end

  protected

  def add_csrf_cookie
    cookies['CSRF-Token'] = form_authenticity_token if protect_against_forgery?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ReactOnRails::Controller

  def index
    redux_store(
        'ticketsStore',
        props: render_to_string(template: "api/v1/tickets/index.json.jbuilder", locals: { tickets: current_user ? current_user.tickets.all : [] }, format: :json)
    )

    respond_to do |format|
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agent/tickets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= t('.title') %></h1>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Title</th>
            <th>Status</th>
            <th>User name</th>
            <th>Agent name</th>
            <th>Created at</th>
            <th>Updated at</th>
          </tr>
          </thead>
          <tbody>
          <% collection.each do |ticket| %>
              <tr>
                <td><%= link_to ticket.title, agent_ticket_path(ticket) %></td>
                <td><%= ticket.status %></td>
                <td><%= ticket.user ? ticket.user.name : '-' %></td>
                <td><%= ticket.agent ? ticket.agent.name : '-' %></td>
                <td><%= l ticket.created_at, format: :short %></td>
                <td><%= l ticket.updated_at, format: :short %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/agent/tickets/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <h1><%= resource.title %> (<%= resource.status %>)</h1>
      <%= link_to 'Back', agent_tickets_path, class: %w(btn btn-default) %>
      <%= simple_form_for [:agent, resource] do |f| %>
          <%= f.association :agent, collection: User.agent %>
          <%= f.button :submit %>
      <% end %>
      <%= simple_form_for resource.comments.new, url: agent_ticket_comments_path(resource) do |f| %>
          <%= f.input :content %>
          <%= f.button :submit %>
      <% end %>
      <div class="form-group text-right">
        <% if resource.status == 'open' %>
            <%= button_to 'Close', agent_ticket_path(ticket: {status: 'closed'}), method: :patch, class: 'btn btn-success' %>
        <% else %>
            <%= button_to 'Reopen', agent_ticket_path(ticket: {status: 'open'}), method: :patch, class: 'btn btn-danger' %>
        <% end %>
      </div>
      <% resource.comments.includes(:user).order(id: :desc).each do |resource| %>
          <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"> <%= resource.user.name %>
              @ <%= l resource.created_at, format: :short %> </h3></div>
            <div class="panel-body"><%= simple_format resource.content %> </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/agent/users/_form.html.erb
<%= simple_form_for([:agent, resource], html: { class: 'form-horizontal' }) do |f| %>
  <%= f.input :email %>
  <%= f.input :name %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :agent %>
  <%= f.input :admin %>
  <%= f.button :submit %>
<% end %>

app/views/agent/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <h1>User: <%= resource.name %></h1>
      <%= render partial: 'agent/users/form', locals: {resource: resource} %>
    </div>
  </div>
</div>

app/views/agent/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1><%= t('.title') %></h1>
      <%= link_to 'New', new_agent_user_path, class: %w(btn btn-primary) %>
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Created at</th>
            <th>Agent?</th>
            <th>Admin?</th>
          </tr>
          </thead>
          <tbody>
          <% collection.each do |user| %>
              <tr>
                <th><%= link_to user.name, agent_user_path(user) %></th>
                <th><%= mail_to user.email %></th>
                <th><%= l user.created_at, format: :short %></th>
                <th><%= user.agent ? 'yes' : 'no' %></th>
                <th><%= user.admin ? 'yes' : 'no' %></th>
              </tr>
          <% end %></tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/agent/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
      <h1><%= t('.title')%></h1>
      <%= render partial: 'agent/users/form', locals: {resource: resource} %>
    </div>
  </div>
</div>

app/views/agent/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <h1>User: <%= resource.name %></h1>
      <%= link_to 'Edit', edit_agent_user_path(resource), class: %w(btn btn-primary) %>
      <%= link_to 'Back', agent_users_path, class: %w(btn btn-default) %>
      <dl class="dl-horizontal">
        <dt>Email</dt>
        <dd><%= mail_to resource.email %> </dd>
        <dt>Created at</dt>
        <dd><%= l resource.created_at, format: :short %> </dd>
        <dt>Agent?</dt>
        <dd><%= resource.agent ? 'yes' : 'no' %> </dd>
        <dt>Admin?</dt>
        <dd><%= resource.admin ? 'yes' : 'no' %> </dd>
      </dl>
    </div>
  </div>
</div>

app/views/layouts/agent.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'agent', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'agent', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar" />
          <span class="icon-bar" />
          <span class="icon-bar" />
        </button>
        <a class="navbar-brand" href="/agent">Tickets</a>
      </div>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="nav navbar-nav">
          <li>
            <a href="<%= agent_root_path %>"><%= t('agent.tickets.index.title') %></a>
          </li>
          <% if current_user.admin? %>
            <li>
              <a href="<%= agent_users_path %>"><%= t('agent.users.index.title') %></a>
            </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="<%= destroy_user_session_path %>" data-method="delete">Sign out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickets</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <%= redux_store_hydration_data %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'agent', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'agent', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<%= react_component('TicketsApp', prerender: false) %>